### PR TITLE
SLRead: Create "how to" house page

### PR DESCRIPTION
**Pull request by SLRead**

### CODE REVIEW

**Review by luxumbra — COMMENTED** [review]
Hey @SLRead, did you mean to not add the how to house page to the main nav? :)

**Review by hammadj — APPROVED** [review]
Looks good! If you want to include a link to the how-to-house in the sidebar you will also need to edit the sidebars.js file

**Comment by SLRead** [comment]
sidebar.js updated

Sorry I missed that initially.  Should be all ready now.

**Comment by SLRead** [comment]
> Hey @SLRead, did you mean to not add the how to house page to the main nav? :)

I didn't mean to, no... Corrected that oversight now. Thanks!

**Review by peth-yursick — APPROVED** [review]

**Review by peth-yursick — APPROVED** [review]

**Pull request merged**
