### PR TITLE
Kittyslasher how to play meta game 12.11.2021

### PR DESCRIPTION
**Pull request by kittyslasher**
Removed the extra bullet from How to play meta game page. Also added quotation marks around "How many Seeds is enough Seeds?"

### CODE REVIEW

**Review by luxumbra — APPROVED** [review]
Thanks for updating this info @kittyslasher 🙏🏻 2 commits probably would have been enough here tbh but no worries.

**Review by luxumbra — CHANGES_REQUESTED** [review]
Actually, it is probably worth updating the pool address to reflect our migration to Polygon. 
Balancer trade page on polygon: https://polygon.balancer.fi/#/trade/weth/0xeaecc18198a475c921b24b8a6c1c1f0f5f3f7ea0/

**Comment by luxumbra** [comment]
@kittyslasher are you available to add in the new pool address and also sort the conflicting file? No worries if not, I or someone else can pick it up.

**Comment by kittyslasher** [comment]
I'll look into this today.

**Comment by luxumbra** [comment]
> I'll look into this today.

Amazing, thank you.

**Comment by Baconaetor** [comment]
I'm going to close this out for now, as the change on the join page already seems to be implemented, this PR is pretty old, and I'm not sure why it's suggesting to start with 50 seeds. @kittyslasher the original fix with the extra bullet and incorrect link still needs to be done, so feel free to open a new PR for that or clean-up this one and reopen it.

**Pull request closed without merging**
