### PR TITLE
Create CupOJosephs-Becoming-An-Ethereum-Developer-Roadmap-and-Guide.md

### PR DESCRIPTION
**Pull request by jschiarizzi**

### CODE REVIEW

**Review by firattale — APPROVED** [review]
LGTM

**Review by peth-yursick — APPROVED** [review]

**Comment by jschiarizzi** [comment]
> You gotta update the sidebar.js file when you add a new page. This page won't show on the wiki without the update. Also, PR's need some descriptors when you create them, to make it easier for us to review.
> 
> If you need help with this let me know and I can help you out with it!

some help with that would be great! I don't know where that goes exactly.

**Comment by peth-yursick** [comment]
> > You gotta update the sidebar.js file when you add a new page. This page won't show on the wiki without the update. Also, PR's need some descriptors when you create them, to make it easier for us to review.
> > If you need help with this let me know and I can help you out with it!
> 
> some help with that would be great! I don't know where that goes exactly.

Huh, I was sure I saw it added there before I merged 🤨
But here: https://github.com/MetaFam/metagame-wiki/blob/master/sidebars.js
Every time someone adds a new post, it needs to be included in the right section with a path to where its located in the codebase (until someone upgrades us to the new docusaurus. Still interested in doing that @jonathanprozzi?)

**Comment by peth-yursick** [comment]
Don't worry about it since I already merged, I'll just include the change in my PR

**Pull request merged**
