### PR TITLE
Added Playbooks to CMS GUI

### LINKED ISSUE #253: Playbooks not appearing as one of the categories in the editing GUI
Wiki:
image

Edit mode:
image

### PR DESCRIPTION
**Pull request by jonathanprozzi**
This PR resolves #253 -- Since NetlifyCMS is a bit tricky to test locally, I cloned our repo and made a version on a personal Vercel deploy for testing:

playbooks-cms-ui

Here's the link to my cloned deploy: https://metagame-wiki-jp.vercel.app/admin#/

If you log in with your creds you'll be able to test it out. I didn't actually create a Playbook with this since I wasn't sure how that would impact our existing content, but wanted to at least get these added to the collections UI.

### CODE REVIEW

**Comment by luxumbra** [comment]
> If you log in with your creds you'll be able to test it out. I didn't actually create a Playbook with this since I wasn't sure how that would impact our existing content, but wanted to at least get these added to the collections UI.

Hey @jonathanprozzi I wasn't able to log in to your instance, so haven't been able to test this. I will check out your branch and try it on mine.

**Comment by jonathanprozzi** [comment]
> > If you log in with your creds you'll be able to test it out. I didn't actually create a Playbook with this since I wasn't sure how that would impact our existing content, but wanted to at least get these added to the collections UI.
> 
> 
> 
> Hey @jonathanprozzi I wasn't able to log in to your instance, so haven't been able to test this. I will check out your branch and try it on mine. 

Interesting - thanks for trying! I'm wondering if your branch will work for your login creds only. This one worked with my GH login but I'm wondering if only I can on my cloned version.

**Comment by jonathanprozzi** [comment]
@luxumbra  Thinking about that more -- I wonder if it's because I'm the only one as a contributor on my cloned version. Since it uses GitHub auth it may be checking for that. Did the login form appear and your creds not work?

**Comment by dysbulic** [comment]
> Did the login form appear and your creds not work?


https://user-images.githubusercontent.com/181523/125789282-88833a7d-1c7a-46dc-9409-9ea95494a9be.mp4

**Comment by jonathanprozzi** [comment]
> > Did the login form appear and your creds not work?
> 
>  2021-07-15@08.35.34.mp4

I can’t seem to load the vid. Will try again from my laptop. Thanks!

**Comment by luxumbra** [comment]
> @luxumbra Thinking about that more -- I wonder if it's because I'm the only one as a contributor on my cloned version. Since it uses GitHub auth it may be checking for that. Did the login form appear and your creds not work?

Yeah, that is most likely the issue. Thanks for posting the vid.

**Comment by jonathanprozzi** [comment]
> > Did the login form appear and your creds not work?
> 
>  2021-07-15@08.35.34.mp4

Thanks for the vid, that's super helpful (was able to load on my laptop). I'm trying to think of the best way to allow for us to test this on a cloned repo before we integrate into the main wiki.

I'm going to change the api callback url for the cloned repo and see if that resolves it. It's working for me but I suspect it has to do with that.

I'll play with it and report back -- thanks!

**Review by peth-yursick — APPROVED** [review]
Gonna play its all good but you know I don't actually understand code, right? 😂

**Comment by luxumbra** [comment]
> Gonna play its all good but you know I don't actually understand code, right?

@peth-yursick I tend to ask for your review or tag you if it is for visual / content approval. I don't remember asking for your review on this one though 😅

**Comment by jonathanprozzi** [comment]
> > Gonna play its all good but you know I don't actually understand code, right?
> 
> @peth-yursick I tend to ask for your review or tag you if it is for visual / content approval. I don't remember asking for your review on this one though 😅

I mentioned it to peth since I saw you tagged the other for review -- my bad! Thanks @peth-yursick for reviewing :)

**Pull request merged**
