### PR TITLE
Removing things, changing home, let's see

### PR DESCRIPTION
**Pull request by peth-yursick**
Tried removing the home screen & a few other categories, lets see if it works 🤷‍♂️

### CODE REVIEW

**Comment by luxumbra** [comment]
If I build your branch locally I get the following error

image

Your link to `/docs/wtf-is-metagame/metafam-way#metafam` is a dead end - you need to create that page `metafam-way.md` in the `wtf-is-metagame` directory or link to a diff page that does exist. 👍🏻 

image

**Review by luxumbra — COMMENTED** [review]
If I build your branch locally I get the following error

image

Your link to `/docs/wtf-is-metagame/metafam-way#metafam` is a dead end - you need to create that page `metafam-way.md` in the `wtf-is-metagame` directory or link to a diff page that does exist. 👍🏻 

👇🏻  this shows the lack of metafam-way
image

**Comment by peth-yursick** [comment]
> If I didn't know you better, I'd say you were farming XP. 👀 😄

If we're lowering wiki XP weight by a shitton to normalize typos & other small fixes like we said we would, then I still won't get enough XP for doing the full overhaul - should start splitting it into multiple PRs 😂

> Your link to /docs/wtf-is-metagame/metafam-way#metafam is a dead end point it to you need to create that page metafam-way.md in the wtf-is-metagame directory or link to a diff page that does exist metamanifesto.md. 👍🏻

Fucking glossary man! 🤣
This is exactly why I'm hesitant at changing actual file names. There's a bunch that need to be updated as they're not matching page titles but idk how many links I'd break lol - internal links breaking are at least detected, normal links aren't..

Should be fixed now

**Comment by luxumbra** [comment]
> > If I didn't know you better, I'd say you were farming XP. eyes smile
> 
> If we're lowering wiki XP weight by a shitton to normalize typos & other small fixes like we said we would, then I still won't get enough XP for doing the full overhaul - should start splitting it into multiple PRs joy

that was done maybe a year ago. I was pulling your leg but you do make a good point - Probs wanna make it a did-a-thing post.

**Review by luxumbra — APPROVED** [review]
LGTM 🚀

**Pull request merged**
