### PR TITLE
Tldr metaos

### PR DESCRIPTION
**Pull request by peth-yursick**

### CODE REVIEW

**Comment by Baconaetor** [comment]
> _No description provided._

@peth-yursick 🤨

**Comment by peth-yursick** [comment]
> > _No description provided._
> 
> @peth-yursick 🤨

I was pretty annoyed by not being able to open the PR & merging directly to master instead
image

Also the title pretty much is the description, you can see there are only 2 files changed. One of them is adding tl;dr & the other one is adding metaos to the sidebar
image

**Review by luxumbra — CHANGES_REQUESTED** [review]
I know it is mega frustrating to have these issues with what should be a simple update. One day we will have a sane workflow for editorial updates. Soon ™️ 

The `tl;dr.md` filename is not invalid but sidebars.js doesn't like it and fails to build with it referenced in the file. I've renamed the file and the reference to it in sidebars.js and can push the update to this PR if you like.

**Comment by Baconaetor** [comment]
I don't know why the preview isn't deploying. . .Or why our sidebar.js file was so fucked. I'll look over it again in the morning if Lux doesn't beat me to it.

**Review by Baconaetor — APPROVED** [review]
Got this ironed out. We're still going to have to fix the metaos page though. Filetype rename and un- omment it's sidebar entry. Same needs to be done for CupOJoseph's playbook though. I'm thinking of doing it in another PR.

**Comment by Baconaetor** [comment]
@peth-yursick you can't add unrecognized files to sidebar. js. Moving forward all files added need to have their sidebar edits in the same PR. This back and worth with files and sidebars just makes things complicated and breaks them. I'm tempted to just close this PR and have a new one created, but maybe @luxumbra can fix it. I also might take a look later if I have the time, because the changes needed to fix the PR at this point can't be done through the github UI I don't think.

**Comment by luxumbra** [comment]
> @peth-yursick you can't add unrecognized files to sidebar. js. Moving forward all files added need to have their sidebar edits in the same PR. This back and worth with files and sidebars just makes things complicated and breaks them. I'm tempted to just close this PR and have a new one created, but maybe @luxumbra can fix it. I also might take a look later if I have the time, because the changes needed to fix the PR at this point can't be done through the github UI I don't think.

I had a fix ready to push, as mentioned in my review comment on the 4th. I'll sort it out tonight. No need to bin the PR.

**Comment by luxumbra** [comment]
I will clean up commits once this is fixed.

**Review by luxumbra — APPROVED** [review]

**Pull request merged**
