### PR TITLE
Add more concise flows in addition to the ones that exist

### PR DESCRIPTION
**Pull request by elihanover**
I thought it would be worthwhile to create a clear introductory flow to MetaGame.  You can think of it as a _minimum viable read_.  The sections that exist are essential longer reads, but the idea of this was to create a TL;DR type flow that gives people the essence of MetaGame (which I think would also help to onboard guilds).  I wanted to try to keep our value pitch as concise as possible.

On the Discord, I suggested that @peth-yursick spice up the Intro with some MeteGame flair, something that he's more familiar with than myself.

Looking forward to getting a discussion going. 🐙

For ease, you can explore the changes [here](https://metagame-wiki.elihanover.vercel.app/docs/Players/start-here)

### CODE REVIEW

**Comment by krzysu** [comment]
I like it!, What do you think @peth-yursick ?
If this PR is accepted, @elihanover please remove all commented-out code before merging to keep the code base clean.

**Comment by krzysu** [comment]
@peth-yursick you cannot rename files without updating all places where that file is referenced, that breaks the build. I will revert your last commit

**Comment by peth-yursick** [comment]
nvm, yeah, still need to update index.js

**Comment by krzysu** [comment]
also `docs/handbook/where-to-start.md`

**Pull request merged**
