### PR TITLE
Manifesto

### PR DESCRIPTION
**Pull request by burrrata**
Now @peth-yursick's Manifesto shows up on the sidebar. Also renamed the file to `metamanifesto.mdx` because the old file mixed hyphens and underscores and it was really long. Also reorganized the other Manifesto docs.

### CODE REVIEW

**Comment by burrrata** [comment]
Made manifesto section first to close out https://github.com/MetaFam/metagame-wiki/pull/19

**Comment by burrrata** [comment]
Addresses erroneous PRs (#19 and #21)

**Comment by burrrata** [comment]
@peth-yursick Please review and merge!

**Comment by dmvt** [comment]
looks like you have some merge conflicts @burrrata

**Comment by peth-yursick** [comment]
> 
> 
> @peth-yursick Please review and merge!

a lot of what's inside was already updated or completely changed, eg. the sidebar..
wouldn't want to revert

**Pull request closed without merging**
