### PR TITLE
WIP: 134 moar design tweaks

### PR DESCRIPTION
**Pull request by luxumbra**
Updates to the design based on feedback in #134 and Discord. I've also got a bit creative with the homepage, so it would be great to get feedback on the homepage changes mainly.  Thanks.

### CODE REVIEW

**Review by hammadj — CHANGES_REQUESTED** [review]
Text seems a bit small and hard to read, would be nice to bump it up a bit. Also, the mobile navigation button that was on the bottom left isnt there anymore:

image

Before:
image

**Comment by luxumbra** [comment]
Sorry for all the preview deploys & unnecessary allowance usage. Stupidly forgot to check a couple of things before pushing. 

@hammadj you'll notice the mobile menu button is back. :sweat_smile:

**Comment by hammadj** [comment]
No problem! Yea mobile button is back and font size for main text looks better, but the font sizes for the sidebar is even smaller than before now and really hard to read:
image

**Review by hammadj — APPROVED** [review]

**Comment by luxumbra** [comment]
Issues should be sorted now. I don't think I have merge permissions.

**Comment by luxumbra** [comment]
@hammadj I am not able to merge PRs, would you be able to do it when you have a chance? :pray:

**Pull request merged**
