### PR TITLE
removed the undesirable /

### PR DESCRIPTION
**Pull request by luxumbra**
...that i think is breaking the og site image

### CODE REVIEW

**Comment by luxumbra** [comment]
@felixbbertrand 👋🏻

**Comment by felixbbertrand** [comment]
@luxumbra not sure why you ping me , I don't have access here

**Comment by luxumbra** [comment]
> @luxumbra not sure why you ping me , I don't have access here . Make sense tho, since the baseURL is set to /

Yeah, noticed I couldn't tag you as reviewer. Are you not able to review?

**Comment by felixbbertrand** [comment]
> > @luxumbra not sure why you ping me , I don't have access here . Make sense tho, since the baseURL is set to /
> 
> Yeah, noticed I couldn't tag you as reviewer. Are you not able to review?

It seems I don't have access

**Comment by luxumbra** [comment]
> It seems I don't have access

It seems I don't have access to add you as a collaborator. @peth-yursick can we add our dude Felix here to the wiki collabs please.

**Comment by luxumbra** [comment]
@peth-yursick could you give this one a review please so the images shows when sharing the wiki url

**Review by mprimi — APPROVED** [review]
Preview looks good so I'm approving, tho there may be some page/link that relies on this slash to be there.

**Comment by luxumbra** [comment]
Many thanks @mprimi

**Pull request merged**
