### PR TITLE
Issue#128 - Design Tweaks

### PR DESCRIPTION
**Pull request by manolingam**
### layout changes
- removed both header and footer
- moved `what-why-how-of-your-dao.md` into _docs/Guilding_ according to the structure provided in `sidebars.js`
- elements are in place and is full screen after removing the header and footer
- disabled theme switcher

### style changes
- site uses dark mode as the one and only mode

For color updates, am not sure about the spec provided in order to match with the components.

### CODE REVIEW

**Review by peth-yursick — APPROVED** [review]

**Comment by peth-yursick** [comment]
Thank you!
The only issue I'm seeing is that you seem to have changed the image URLs which is making them no longer display (at least not in the netlify deployment)
And about the colors issue, is there something I need to clarify or is it just unclear how to implement it?

**Comment by peth-yursick** [comment]
Also not sure if I explained it properly in the issue, but now that everything has been cleaned up, the middle part is leaving a lot of blank space below it. (screenshot attached)
Could you make it appear in the middle of the screen?
image

**Comment by manolingam** [comment]
> The only issue I'm seeing is that you seem to have changed the image URLs which is making them no longer display (at least not in the netlify deployment)
Ah.. okay. Changed the URL path as it wasn't getting displayed earlier on localhost. Will revert that back.
> And about the colors issue, is there something I need to clarify or is it just unclear how to implement it?
Need clarification on accuracy of which color spec is for which particular element.

**Comment by manolingam** [comment]
> Also not sure if I explained it properly in the issue, but now that everything has been cleaned up, the middle part is leaving a lot of blank space below it. (screenshot attached)

Hmm.. that's odd. It was without blank spaces on my browser. Maybe it gets filled in when the images render.

**Comment by peth-yursick** [comment]
> Ah.. okay. Changed the URL path as it wasn't getting displayed earlier on localhost. Will revert that back.
Maybe it has something to do with this: https://github.com/MetaFam/metagame-wiki/pull/127
(a reupload of assets because there was a problem with them, if you can review it maybe it should work)

> Need clarification on accuracy of which color spec is for which particular element.
Can't help you with that unfortunately, I wanted to change the colors myself but couldn't figure it out because the file I linked only references the pink colors, not all the menus and background. 

> Hmm.. that's odd. It was without blank spaces on my browser. Maybe it gets filled in when the images render.
It probably depends on screen size, so if you have a smaller screen there is no blank space but when I open it, it looks weird. If it rendered in the middle for everyone then it should hopefully work for everyone.

**Comment by manolingam** [comment]
Have reverted back the image URL path. Let me know if that renders in the deployment. And am not able to see this screen size issue in all of my browsers & screen sizes. Let's see if the image render fixes it.

**Pull request merged**
