### PR TITLE
Design changes for #134

### PR DESCRIPTION
**Pull request by luxumbra**
These changes cover @peth-yursick requests in #134. I also added some more responsive tweaks to font-sizes and whitespace in the sidebar mainly. I feel the centre column needs some more space at the top?

Feedback welcomed

### CODE REVIEW

**Review by peth-yursick — APPROVED** [review]

**Comment by peth-yursick** [comment]
The sidebar is too wide now, it leaves a lot of extra space and it moved the text from middle to the right..
image
Actually, it seems like it was my fault because of the example I provided in the issue 
image
The reason for the alignment in my screenshot was because I couldn't screenshot the whole screen without zooming out 😅 Sorry..
Here it is zoomed out:
image
Is it not possible to make the sidebar look like that or was this just a WIP PR?

**Comment by peth-yursick** [comment]
Also just saw your comment in the issue... It seems like it looks completely different to me than it does to you :S

**Comment by luxumbra** [comment]
It's mainly to get feedback and to catch issues. :sweat_smile: So the content sits centred on the screen and the sidebar fills the space as opposed to the content shifting right to accommodate the sidebar?

**Comment by luxumbra** [comment]
> Also just saw your comment in the issue... It seems like it looks completely different to me than it does to you :S

yeah, it does. It looks like this on my local build. 

image

Ah, i see :monocle_face: Looks like the classes I hooked onto in the CSS change slightly during the build. I'll sort that.

**Comment by luxumbra** [comment]
I've updated the CSS now and it now looks on preview as it does on my local build. :smile:

**Review by peth-yursick — APPROVED** [review]

**Comment by peth-yursick** [comment]
> 
> 
> I've updated the CSS now and it now looks on preview as it does on my local build. 😄

Awesome, thank you!

**Review by peth-yursick — APPROVED** [review]

**Pull request merged**
