### PR TITLE
#128 design tweaks

### PR DESCRIPTION
**Pull request by luxumbra**
Changes as per  @peth-yursick comments.
* Changed colors to match MyMeta
* MyMeta font used for body copy
* Removed white divider
* Top navbar hidden
* Removed space for footer
* Vertically centred homepage content.

I am wondering if it's worth adding a small logo at the top of the sidebar?

### CODE REVIEW

**Review by dan13ram — APPROVED** [review]

**Review by dan13ram — CHANGES_REQUESTED** [review]
Hey @luxumbra, some of these checks are failing. 
Can you please fix them?

**Comment by luxumbra** [comment]
Yeah, sorry about that! I'll sort them.

**Comment by peth-yursick** [comment]
> 
> 
> Yeah, sorry about that! I'll sort them.

Still seems to be failing the checks :S

**Comment by luxumbra** [comment]
As well as the window object issue, there was a : in the Manifesto page title that caused validation issues - I had removed it but hadn't committed the change.

**Comment by peth-yursick** [comment]
> 
> 
> As well as the window object issue, there was a : in the Manifesto page title that caused validation issues - I had removed it but hadn't committed the change.

Awesome, thank you!
Merging now

**Review by peth-yursick — APPROVED** [review]

**Comment by peth-yursick** [comment]
To confirm, this adds up to everything that was requested in the issue https://github.com/MetaFam/metagame-wiki/issues/128?
I can close the issue?

**Comment by luxumbra** [comment]
> To confirm, this adds up to everything that was requested in the issue #128?
> I can close the issue?

Yes, this ties up what was left after saimano passed the baton to me. 

At some point, it would be good to spend some time on the responsive aspects of the wiki

**Pull request merged**
