### PR TITLE
Cms/great houses/house of nf ts

### PR DESCRIPTION
**Pull request by Techniciann9ne**
Small addition and spelling corrections

### CODE REVIEW

**Review by Baconaetor — CHANGES_REQUESTED** [review]
The backslashes you added in the header break the link formatting. Also what are you using to edit these pages? It changes up a lot of the formatting in a weird way.

**Comment by Baconaetor** [comment]
Actually, those header links appear to already be broken. . .Might as well fix that in this PR though. . .

**Comment by luxumbra** [comment]
> Actually, those header links appear to already be broken. . .Might as well fix that in this PR though. . .

@Techniciann9ne are you available to fix the issues @Baconaetor mentioned? If not, let us know and I or someone else can sort them. Thanks

**Comment by Baconaetor** [comment]
I'm gonna close this out as you haven't responded. If you want to pick this up feel free! Just let us know or submit a new PR.

**Pull request closed without merging**
