### PR TITLE
Reinstating the navbar ready for the DAO meetup

### PR DESCRIPTION
**Pull request by luxumbra**
Navbar returns for the DAO meetup:

Centred and updated crystal icon and added a glow / flicker effect on hover. If it's OTT or cheesy, I'll remove it but i thought it gave the icon some extra energy..

### CODE REVIEW

**Comment by luxumbra** [comment]
Actually, looking at this, I need to reduce the height of the navbar by like 5px to avoid a bit of overlap with the highfidelity menu when open.

**Review by hammadj — COMMENTED** [review]
There's this weird flashing thing thats happening when I hover over the MetaGame icon. Otherwise looks good!

**Comment by luxumbra** [comment]
> There's this weird flashing thing thats happening when I hover over the MetaGame icon. Otherwise looks good!

That was me trying to be a bit creative. I'll remove it. I am just doing a couple of tweaks before I push that. Thanks for reviewing.

**Comment by luxumbra** [comment]
@hammadj are you ok with just the glow on hover?

**Review by hammadj — APPROVED** [review]

**Comment by hammadj** [comment]
Looks good! merged

**Comment by luxumbra** [comment]
Thanks dude. :ok_hand:

**Pull request merged**
